### ISSUE TITLE
Priority 1 - Duplicate loans in submitted status

### ISSUE THREAD

**Issue by MathiDuruva** [mifos-x-customization/temp-os#3]
Currently the mifos is creating multiple loan application on single click. Even in submitted status also, one client should have only one loan application.

**Comment by maektwain** [comment]
Yeah , I think as long as submitted status is there , I think it should not be a point of conflict since it is not approved you can just delete it, but question is , is it happening as a bug creating duplicate submitted loans.

**Comment by Meena88** [comment]
yes , indeed, even when the user doesn't make double clicks, mifos create double, triple loans for a particular group of clients, so make a condition that there should be only one loan for a client in status 100 at a time.

**Comment by Meena88** [comment]
ofcourse they can be deleted, i consider that to be a waste of our productive time, we have alteast 15 members in a group, if there is a double loan, my user need to go delete the loan all 15 members in the group, and if the same happens for multiple users , which will be a headache for us to go delete it every now and then, so fix this once and for all.

**Comment by maektwain** [comment]
I tested it online.  There was no duplication happening with single client under bulk loan. 

Actually what you are doing is when you select the client while submitting a loan for bulk which has already been applied , the ideal scenario would be to provide the loans in one go that is why bulk loan, that is where, its going wrong plus putting the validation seems illogical to me. Please advice.

**Comment by Meena88** [comment]
i need to have only one loan with status 100 for a client , this is my requirement, even though they are selected for a second loan, the system should not allow the user to submit loan for that client
