### ISSUE TITLE
Priority 6 - Duplicate journal entries during add manual journal entry

### ISSUE THREAD

**Issue by MathiDuruva** [mifos-x-customization/temp-os#6]
When i add manual journal entries , the entries are happening twice which is not allowing to tally the data. 

note :Inconsistent

**Comment by maektwain** [comment]
Could your provide me some examples on the working instance.

**Comment by Meena88** [comment]
you mean journal ids from server? sure  i'll share them

**Comment by Meena88** [comment]
| id      | account_id | office_id | reversal_id | currency_code | transaction_id | loan_transaction_id | savings_transaction_id | client_transaction_id | reversed | ref_num | manual_entry | entry_date | type_enum | amount       | description                                | entity_type_enum | entity_id | createdby_id | lastmodifiedby_id | created_date        | lastmodified_date   | is_running_balance_calculated | office_running_balance | organization_running_balance | payment_details_id | share_transaction_id |
+---------+------------+-----------+-------------+---------------+----------------+---------------------+------------------------+-----------------------+----------+---------+--------------+------------+-----------+--------------+--------------------------------------------+------------------+-----------+--------------+-------------------+---------------------+---------------------+-------------------------------+------------------------+------------------------------+--------------------+----------------------+
| 1220763 |         65 |         1 |     1226025 | INR           | 8ed6897045cf   |                NULL |                   NULL |                  NULL |        1 |         |            1 | 2019-09-30 |         2 |  5004.000000 | NEFT/RETURN/AXISP00073588490/R03/Tamilmani |             NULL |      NULL |            3 |                 3 | 2019-10-08 13:16:39 | 2019-10-08 13:25:44 |                             1 |         1052069.920000 |               1102069.920000 |               NULL |                 NULL |
| 1220765 |         32 |         1 |     1226026 | INR           | 8ed6897045cf   |                NULL |                   NULL |                  NULL |        1 |         |            1 | 2019-09-30 |         1 |  5004.000000 | NEFT/RETURN/AXISP00073588490/R03/Tamilmani |             NULL |      NULL |            3 |                 3 | 2019-10-08 13:16:39 | 2019-10-08 13:25:44 |                             1 |        11681065.830000 |              11631065.830000 |               NULL |                 NULL |
| 1227932 |         65 |         1 |     1227934 | INR           | 8ed68f84aed3   |                NULL |                   NULL |                  NULL |        1 |         |            1 | 2019-09-30 |         2 |  5004.000000 | NEFT/RETURN/AXISP00073920535/R03/Selvi     |             NULL |      NULL |            3 |                 3 | 2019-10-08 13:33:39 | 2019-10-08 13:33:53 |                             1 |          613153.920000 |                663153.920000 |               NULL |                 NULL |
| 1227933 |         32 |         1 |     1227935 | INR           | 8ed68f84aed3   |                NULL |                   NULL |                  NULL |        1 |         |            1 | 2019-09-30 |         1 |  5004.000000 | NEFT/RETURN/AXISP00073920535/R03/Selvi     |             NULL |      NULL |            3 |                 3 | 2019-10-08 13:33:39 | 2019-10-08 13:33:53 |                             1 |        12119981.830000 |              12069981.830000 |               NULL |                 NULL |
| 1227938 |         65 |         1 |     1228392 | INR           | 8ed68fbcd50b   |                NULL |                   NULL |                  NULL |        1 |         |            1 | 2019-09-30 |         2 |  6012.000000 | NEFT/RETURN/AXISP00073920535/R03/Selvi     |             NULL |      NULL |            3 |                 3 | 2019-10-08 13:34:16 | 2019-10-08 15:13:24 |                             1 |          620173.920000 |                670173.920000 |               NULL |                 NULL |
| 1227939 |         32 |         1 |     1228393 | INR           | 8ed68fbcd50b   |                NULL |                   NULL |                  NULL |        1 |         |            1 | 2019-09-30 |         1 |  6012.000000 | NEFT/RETURN/AXISP00073920535/R03/Selvi     |             NULL |      NULL |            3 |                 3 | 2019-10-08 13:34:16 | 2019-10-08 15:13:24 |                             1 |        12112961.830000 |              12062961.830000 |               NULL |                 NULL |
| 1232828 |         66 |         1 |     1232830 | INR           | 8ed88b2bdb43   |                NULL |                   NULL |                  NULL |        1 |         |            1 | 2019-09-30 |         2 | 30020.000000 | Cash Deposit                               |             NULL |      NULL |            3 |                 3 | 2019-10-09 13:13:09 | 2019-10-09 13:13:20 |                             1 |          282587.190000 |                282587.190000 |               NULL |                 NULL |
| 1232829 |         32 |         1 |     1232831 | INR           | 8ed88b2bdb43   |                NULL |                   NULL |                  NULL |        1 |         |            1 | 2019-09-30 |         1 | 30020.000000 | Cash Deposit                               |             NULL |      NULL |            3 |                 3 | 2019-10-09 13:13:09 | 2019-10-09 13:13:20 |                             1 |        11782260.830000 |              11732260.830000 |               NULL |                 NULL |

**Comment by Meena88** [comment]
these are entry from live server m1, they were made on 30-09-2019 , mifos made one than one entries for these journals, so we manually reversed them to make things right.

**Comment by maektwain** [comment]
So I am closing this issue.
